version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "arula-ai"
    assignees:
      - "arula-ai"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
