name: Java Security Scan

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
        cache: maven

    - name: Install dependencies and run tests
      run: mvn -B clean verify

    - name: Run dependency analysis
      run: mvn -B dependency:tree

    - name: Upload Jacoco coverage report
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: target/site/jacoco

    - name: Check coverage threshold
      run: |
        if [ ! -f target/site/jacoco/jacoco.csv ]; then
          echo "Jacoco report missing"
          exit 1
        fi
        COVERAGE=$(awk -F',' 'NR>1 { covered+=$8; total+=$9 } END { if (total==0) print 0; else printf "%.2f", (covered/total)*100 }' target/site/jacoco/jacoco.csv)
        echo "Instruction coverage: $COVERAGE%"
        if (( $(echo "$COVERAGE < 60" | bc -l) )); then
          echo "Coverage is below 60% threshold"
          exit 1
        fi

    - name: Package application
      run: mvn -B package
